const o = false;
const l = true;
const characterMap = {
	0: [
		[o, o, l, l, l, o, o],
		[o, l, o, o, l, l, o],
		[l, l, o, o, o, l, l],
		[l, l, o, o, o, l, l],
		[l, l, o, o, o, l, l],
		[o, l, l, o, o, l, o],
		[o, o, l, l, l, o, o],
	],
	1: [
		[o, o, o, l, l, o, o],
		[o, o, l, l, l, o, o],
		[o, o, o, l, l, o, o],
		[o, o, o, l, l, o, o],
		[o, o, o, l, l, o, o],
		[o, o, o, l, l, o, o],
		[o, l, l, l, l, l, l],
	],
	2: [
		[o, l, l, l, l, l, o],
		[l, l, o, o, o, l, l],
		[o, o, o, o, l, l, l],
		[o, o, l, l, l, l, o],
		[o, l, l, l, l, o, o],
		[l, l, l, o, o, o, o],
		[l, l, l, l, l, l, l],
	],
	3: [
		[o, l, l, l, l, l, l],
		[o, o, o, o, l, l, o],
		[o, o, o, l, l, o, o],
		[o, o, l, l, l, l, o],
		[o, o, o, o, o, l, l],
		[l, l, o, o, o, l, l],
		[o, l, l, l, l, l, o],
	],
	4: [
		[o, o, o, l, l, l, o],
		[o, o, l, l, l, l, o],
		[o, l, l, o, l, l, o],
		[l, l, o, o, l, l, o],
		[l, l, l, l, l, l, l],
		[o, o, o, o, l, l, o],
		[o, o, o, o, l, l, o],
	],
	5: [
		[l, l, l, l, l, l, o],
		[l, l, o, o, o, o, o],
		[l, l, l, l, l, l, o],
		[o, o, o, o, o, l, l],
		[o, o, o, o, o, l, l],
		[l, l, o, o, o, l, l],
		[o, l, l, l, l, l, o],
	],
	6: [
		[o, o, l, l, l, l, o],
		[o, l, l, o, o, o, o],
		[l, l, o, o, o, o, o],
		[l, l, l, l, l, l, o],
		[l, l, o, o, o, l, l],
		[l, l, o, o, o, l, l],
		[o, l, l, l, l, l, o],
	],
	7: [
		[l, l, l, l, l, l, l],
		[l, l, o, o, o, l, l],
		[o, o, o, o, l, l, o],
		[o, o, o, l, l, o, o],
		[o, o, l, l, o, o, o],
		[o, o, l, l, o, o, o],
		[o, o, l, l, o, o, o],
	],
	8: [
		[o, l, l, l, l, o, o],
		[l, l, o, o, o, l, o],
		[l, l, l, o, o, l, o],
		[o, l, l, l, l, o, o],
		[l, o, o, o, o, l, l],
		[l, o, o, o, o, l, l],
		[o, l, l, l, l, l, o],
	],
	9: [
		[o, l, l, l, l, l, o],
		[l, l, o, o, o, l, l],
		[l, l, o, o, o, l, l],
		[o, l, l, l, l, l, l],
		[o, o, o, o, o, l, l],
		[o, o, o, o, l, l, o],
		[o, l, l, l, l, o, o],
	],
	a: [
		[o, o, l, l, l, o, o],
		[o, l, l, o, l, l, o],
		[l, l, o, o, o, l, l],
		[l, l, o, o, o, l, l],
		[l, l, l, l, l, l, l],
		[l, l, o, o, o, l, l],
		[l, l, o, o, o, l, l],
	],
	b: [
		[l, l, l, l, l, l, o],
		[l, l, o, o, o, l, l],
		[l, l, o, o, o, l, l],
		[l, l, l, l, l, l, o],
		[l, l, o, o, o, l, l],
		[l, l, o, o, o, l, l],
		[l, l, l, l, l, l, o],
	],
	c: [
		[o, o, l, l, l, l, o],
		[o, l, l, o, o, l, l],
		[l, l, o, o, o, o, o],
		[l, l, o, o, o, o, o],
		[l, l, o, o, o, o, o],
		[o, l, l, o, o, l, l],
		[o, o, l, l, l, l, o],
	],
	d: [
		[l, l, l, l, l, o, o],
		[l, l, o, o, l, l, o],
		[l, l, o, o, o, l, l],
		[l, l, o, o, o, l, l],
		[l, l, o, o, o, l, l],
		[l, l, o, o, l, l, o],
		[l, l, l, l, l, o, o],
	],
	e: [
		[l, l, l, l, l, l, l],
		[l, l, o, o, o, o, o],
		[l, l, o, o, o, o, o],
		[l, l, l, l, l, l, o],
		[l, l, o, o, o, o, o],
		[l, l, o, o, o, o, o],
		[l, l, l, l, l, l, l],
	],
	f: [
		[l, l, l, l, l, l, l],
		[l, l, o, o, o, o, o],
		[l, l, o, o, o, o, o],
		[l, l, l, l, l, l, o],
		[l, l, o, o, o, o, o],
		[l, l, o, o, o, o, o],
		[l, l, o, o, o, o, o],
	],
	g: [
		[o, o, l, l, l, l, l],
		[o, l, l, o, o, o, o],
		[l, l, o, o, o, o, o],
		[l, l, o, o, l, l, l],
		[l, l, o, o, o, l, l],
		[o, l, l, o, o, l, l],
		[o, o, l, l, l, l, l],
	],
	h: [
		[l, l, o, o, o, l, l],
		[l, l, o, o, o, l, l],
		[l, l, o, o, o, l, l],
		[l, l, l, l, l, l, l],
		[l, l, o, o, o, l, l],
		[l, l, o, o, o, l, l],
		[l, l, o, o, o, l, l],
	],
	i: [
		[o, o, l, l, l, l, o],
		[o, o, o, l, l, o, o],
		[o, o, o, l, l, o, o],
		[o, o, o, l, l, o, o],
		[o, o, o, l, l, o, o],
		[o, o, o, l, l, o, o],
		[o, o, l, l, l, l, o],
	],
	j: [
		[o, o, o, l, l, l, l],
		[o, o, o, o, o, l, l],
		[o, o, o, o, o, l, l],
		[o, o, o, o, o, l, l],
		[l, l, o, o, o, l, l],
		[l, l, o, o, o, l, l],
		[o, l, l, l, l, l, o],
	],
	k: [
		[l, l, o, o, o, l, l],
		[l, l, o, o, l, l, o],
		[l, l, o, l, l, o, o],
		[l, l, l, l, o, o, o],
		[l, l, o, l, l, o, o],
		[l, l, o, o, l, l, o],
		[l, l, o, o, o, l, l],
	],
	l: [
		[o, l, l, o, o, o, o],
		[o, l, l, o, o, o, o],
		[o, l, l, o, o, o, o],
		[o, l, l, o, o, o, o],
		[o, l, l, o, o, o, o],
		[o, l, l, o, o, o, o],
		[o, l, l, l, l, l, l],
	],
	m: [
		[l, l, o, o, o, l, l],
		[l, l, l, o, l, l, l],
		[l, l, l, l, l, l, l],
		[l, l, l, l, l, l, l],
		[l, l, o, l, o, l, l],
		[l, l, o, o, o, l, l],
		[l, l, o, o, o, l, l],
	],
	n: [
		[l, l, o, o, o, l, l],
		[l, l, l, o, o, l, l],
		[l, l, l, l, o, l, l],
		[l, l, l, l, l, l, l],
		[l, l, o, l, l, l, l],
		[l, l, o, o, l, l, l],
		[l, l, o, o, o, l, l],
	],
	o: [
		[o, l, l, l, l, l, o],
		[l, l, o, o, o, l, l],
		[l, l, o, o, o, l, l],
		[l, l, o, o, o, l, l],
		[l, l, o, o, o, l, l],
		[l, l, o, o, o, l, l],
		[o, l, l, l, l, l, o],
	],
	p: [
		[l, l, l, l, l, l, o],
		[l, l, o, o, o, l, l],
		[l, l, o, o, o, l, l],
		[l, l, l, l, l, l, o],
		[l, l, o, o, o, o, o],
		[l, l, o, o, o, o, o],
		[l, l, o, o, o, o, o],
	],
	q: [
		[o, l, l, l, l, l, o],
		[l, l, o, o, o, l, l],
		[l, l, o, o, o, l, l],
		[l, l, o, o, o, l, l],
		[l, l, o, l, l, l, l],
		[l, l, o, o, l, l, o],
		[o, l, l, l, l, o, l],
	],
	r: [
		[l, l, l, l, l, l, o],
		[l, l, o, o, o, l, l],
		[l, l, o, o, o, l, l],
		[l, l, l, l, l, l, o],
		[l, l, o, l, l, o, o],
		[l, l, o, o, l, l, o],
		[l, l, o, o, o, l, l],
	],
	s: [
		[o, l, l, l, l, o, o],
		[l, l, o, o, l, l, o],
		[l, l, o, o, o, o, o],
		[o, l, l, l, l, l, o],
		[o, o, o, o, o, l, l],
		[l, l, o, o, o, l, l],
		[o, l, l, l, l, l, o],
	],
	t: [
		[o, l, l, l, l, l, l],
		[o, o, o, l, l, o, o],
		[o, o, o, l, l, o, o],
		[o, o, o, l, l, o, o],
		[o, o, o, l, l, o, o],
		[o, o, o, l, l, o, o],
		[o, o, o, l, l, o, o],
	],
	u: [
		[l, l, o, o, o, l, l],
		[l, l, o, o, o, l, l],
		[l, l, o, o, o, l, l],
		[l, l, o, o, o, l, l],
		[l, l, o, o, o, l, l],
		[l, l, o, o, o, l, l],
		[o, l, l, l, l, l, o],
	],
	v: [
		[l, l, o, o, o, l, l],
		[l, l, o, o, o, l, l],
		[l, l, o, o, o, l, l],
		[l, l, l, o, l, l, l],
		[o, l, l, l, l, l, o],
		[o, o, l, l, l, o, o],
		[o, o, o, l, o, o, o],
	],
	w: [
		[l, l, o, o, o, l, l],
		[l, l, o, o, o, l, l],
		[l, l, o, l, o, l, l],
		[l, l, l, l, l, l, l],
		[l, l, l, l, l, l, l],
		[l, l, l, o, l, l, l],
		[l, l, o, o, o, l, l],
	],
	x: [
		[l, l, o, o, o, l, l],
		[l, l, l, o, l, l, l],
		[o, l, l, l, l, l, o],
		[o, o, l, l, l, o, o],
		[o, l, l, l, l, l, o],
		[l, l, l, o, l, l, l],
		[l, l, o, o, o, l, l],
		[l, l, o, o, o, l, l],
	],
	y: [
		[o, l, l, o, o, l, l],
		[o, l, l, o, o, l, l],
		[o, l, l, o, o, l, l],
		[o, o, l, l, l, l, o],
		[o, o, o, l, l, o, o],
		[o, o, o, l, l, o, o],
		[o, o, o, l, l, o, o],
	],
	z: [
		[l, l, l, l, l, l, l],
		[o, o, o, o, l, l, l],
		[o, o, o, l, l, l, o],
		[o, o, l, l, l, o, o],
		[o, l, l, l, o, o, o],
		[l, l, l, o, o, o, o],
		[l, l, l, l, l, l, l],
	],
	",": [
		[o, o, o, o, o, o, o],
		[o, o, o, o, o, o, o],
		[o, o, o, o, o, o, o],
		[o, o, o, o, o, o, o],
		[o, o, l, l, o, o, o],
		[o, o, o, l, o, o, o],
		[o, o, l, o, o, o, o],
	],
	"!": [
		[o, o, o, l, l, o, o],
		[o, o, o, l, l, o, o],
		[o, o, o, l, l, o, o],
		[o, o, o, l, l, o, o],
		[o, o, o, l, l, o, o],
		[o, o, o, o, o, o, o],
		[o, o, o, l, l, o, o],
	],

	"'": [
		[o, o, l, l, o, o, o],
		[o, o, o, l, o, o, o],
		[o, o, l, o, o, o, o],
		[o, o, o, o, o, o, o],
		[o, o, o, o, o, o, o],
		[o, o, o, o, o, o, o],
		[o, o, o, o, o, o, o],
	],
	"&": [
		[o, l, l, l, o, o, o],
		[l, o, o, o, l, o, o],
		[o, l, o, l, o, o, o],
		[o, o, l, o, o, o, o],
		[o, l, o, l, o, l, o],
		[l, o, o, o, l, o, o],
		[o, l, l, l, o, l, l],
	],
	".": [
		[o, o, o, o, o, o, o],
		[o, o, o, o, o, o, o],
		[o, o, o, o, o, o, o],
		[o, o, o, o, o, o, o],
		[o, o, o, o, o, o, o],
		[o, o, l, l, o, o, o],
		[o, o, l, l, o, o, o],
	],
	'"': [
		[o, o, l, o, o, l, o],
		[o, o, l, o, o, l, o],
		[o, o, l, o, o, l, o],
		[o, o, o, o, o, o, o],
		[o, o, o, o, o, o, o],
		[o, o, o, o, o, o, o],
		[o, o, o, o, o, o, o],
	],
	"?": [
		[o, o, l, l, l, o, o],
		[o, l, o, o, o, l, o],
		[o, o, o, o, o, l, o],
		[o, o, o, o, l, o, o],
		[o, o, o, l, o, o, o],
		[o, o, o, o, o, o, o],
		[o, o, o, l, o, o, o],
	],
	"-": [
		[o, o, o, o, o, o, o],
		[o, o, o, o, o, o, o],
		[o, o, o, o, o, o, o],
		[l, l, l, l, l, l, o],
		[o, o, o, o, o, o, o],
		[o, o, o, o, o, o, o],
		[o, o, o, o, o, o, o],
	],
};
